[tool.poetry]
name = "sti-lab"
version = "0.1.0"
description = "Special Token Injection (STI) Ollama + qwen2.5"
authors = ["shoxxdj"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.9"
flask = "^3.0"
requests = "^2.31"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
